### Quartz
# jobClass
jobClassPath: com.lushihao.sharewe.quartzjobs.
jobclass:
  jobList:
    - name: "Job0"
      corn: "0 0 2 * * ?"
      group: "Group0"
    - name: "Job1"
      corn: "0 0 2 * * ?"
      group: "Group1"